/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

import java.util.Random;

/**
 *
 * @author Dinu
 */
public class TestingData_2 {
    
    static public String[] getRandomQuestions() 
    {
        return getRandomQuestions(0);
    }
    
    static public String[] getRandomQuestions(int n) {
        if(n == 0)
            return differentQuestions;
        else
        {
//            int random = 0;
            String[] tmpQuestions = new String[n];
            Random random = new Random();
            for(int i=0; i<n; i++)
            {
                tmpQuestions[i] = differentQuestions[random.nextInt(differentQuestions.length)];
            }
            return tmpQuestions;
        }
    }
    
    static String[] getMainQuestions() {
        return getMainQuestions(0);
    }

    static String[] getMainQuestions(int n)
    {
        return mainQuestions[n];
    }
    
    static String[][] mainQuestions = {
        //Christmas Carol
        { 
        "What is the novel about?",
        "Who is the main character?",
        "Where does the novel take place?",
        "When does the novel take place?",
        "How does it end?",
        "Who is Jacob Marley?",
        "What is Bob Cratchit to Tim Cratchit?",
        "Where does Ebeneezer Scrooge live?",
        "What does Ebeneezer Scrooge do in the novel?",
        "What is London, Scrooge & Marley?",
        "What relationship is between Jacob Marley and Bob Cratchit?",
        "What does Tim Cratchit do?",
        "Who asks for the Christmas day off?",
        "Who shows Scrooge two starved children?",
        "Who visits Bob Cratchit?"
        },
        
        //Great Gatsby
        {
        "What is the novel about?",
        "Who are the main characters?",
        "Where does the novel take place?",
        "When does the novel take place?",
        "How does it begin?",
        "Who is Myrtle Wilson?",
        "Who is Myrtle Wilson to George Wilson?",
        "Wher does Myrtle Wilson live?",
        "What happened in 1917?",
        "Who allows Daisy to ride with Gatsby?",
        "Who is married to George Wilson?",
        "Who commits suicide?",
        "What does Tom Buchanan do?",
        "Who dies?",
        "Where is the Plaza Hotel?"
        }
    };
    
    
    
    static String[] differentQuestions = {"What has forced THE SIMPLIFICATION AND HARMONIZATION OF THE CUSTOM PROCEDURES",
        "What does the creation of the council directive on the education of the migrating workers\' children aim at?",
        "What is the purpose of the negotiation between the European Economic Community and the International Council for the Exploration of the sea ?",
        "What level should the stabilization of greenhouse gas concentrations in the atmosphere reach ?",
        "Why was a combined nomenclature of goods created ?",
        "What is the scope of the council directive on the trading of fodder seeds ?",
        "In which areas will objective information be provided on drugs and drugs addiction ?",
        "What is the purpose of the harmonization of the requirements on the brake systems    ?",
        "What is the foodstuffs for particular nutritional use intended for?",
        "What is the meaning of Article 7a of the Treaty establishing the European Community ?",
        "What is the purpose of the measures on the trade with substances used for the illicit manufacture of narcotic drugs ?",
        "What are the Community\'s procedures for contributing to the struggle against the producers of narcotics?",
        "What  measures are envisaged for the Azores and the Madeira island with respect to some Community products ?",
        "What is the purpose of the necessity to change the rules of the Member States under Article 6 (3) of Directive 85/511/EEC ?",
        "Between which countries is the Framework Agreement for trade and economic cooperation of 2 April 1990?",
        "According to what procedure the Standing Veterinary Committee becomes active ?",
        "Why is it necessary to provide for information about certain foodstuffs in addition to those in Directive 79/112/EEC ?",
        "Which kinds of materials can be sold in a country that is part of the Union ?",
        "Under what circumstances do Community vessels receive the right to carry out fishing in the territorial waters of the Federal and Islamic Republic of Comoros ?",
        "What resolution was adopted by the Council on 10 October 1994?",
        "How is interest in producing silkworm eggs increased ?",
        "What shall the employer provide to each worker ?",
        "What is \'inland surface water'?",
        "What is the carnation yield threatened by ?",
        "What do the processed cereal-based foods have to be prepared from ?",
        "What is the name of the member states' currency from 1 January 1999?",
        "What is the relation of the Euro to the currency of the different member states ?",
        "What is the connection between the European central bank and the Euro ?",
        "What requirements should the development of the single European sky initiative meet ?",
        "Which airport has been the subject of an agreement in 1987?",
        "The thermal stability of which materials is clearly specified to fire regulators in the member states ?",
        "Into which plant may genes be introduced and not raise any doubts about unfavourable consequences for people's health?",
        "Which techniques used for obtaining certain products do not require a special marking ?",
        "Where is the headquarters of the European Maritime Safety Agency ?",
        "Where is the headquarters of the European Aviation Safety Agency ?",
        "Which bands are reserved exclusively for the public European cellular mobile communications system ?",
        "Who is designating the so-called 'transmitting agencies'?",
        "How will a closer contact be established between the European communities and the WHO ?",
        "What does the Council Directive 88/388/EEC of 22 June 1988 refer to ?",
        "According to which regulation should the amounts of compensation for each public service obligation be shown ?",
        "By what procedure are the products , mentioned in Annex I , attested ?",
        "What is the procedure of using casein and caseinates in the production of cheese ?",
        "What is the procedure on providing expert opinion in the veterinary field ?",
        "Which country wishes to export gastropods to the Community ?",
        "In which Directive is information on the labelling included ? ",
        "What is the procedure when, during an investigation, Eurojust needs personal information other than normally authorized ?",
        "How will the interests of consumers and producers be protected from abuse ?",
        "What elements are needed to characterize the high-quality wines produced in a certain region ?",
        "What procedures need to be carried out by a member state, when a CE marking appears within its jurisdiction ?",
        "Which requirements should the CE marking meet ?",
        "Which normative requirements should terminal devices meet ?",
        "Under what circumstances can a railway company offer transportation services without a license ?",
        "What is one of the objects of control in member states in favour of the customers ?",
        "Why should the residue limits of the substances be established ?",
        "Why are the so-called 'registered designations of origin' adopted by some member states ?",
        "Why is it necessary to define the physical and chemical characteristics of the various types of oil ?",
        "Which regulation was corrected by the regulation(EEC) No 2886/89 (5)?",
        "Why is the increase of the weight of the 50 cent coin from 7 g to 7,8 g necessary?",
        "In what circumstances IP may be owned jointly by all participants?",
        "Why are technical requirements for unalloyed steel gas cylinders with capacity up to 150 litres necessary? ",
        "What is  the main reason for Atlas company to export coumarin originating in the PRC?",
        "Why are tungsten carbide and fused tungsten carbide considered one product?  ",
        "Why is lowering the price of agricultural inputs in the Azores necessary?",
        "Why is the production of reconstituted UHT milk from milk powder authorized in Madeira?",
        "Why are the frequencies of 890-915 and 935-960MHz recommended?",
        "On what ground is it considered that regarding the health status for poultry Estonian veterinary services are well organized?",
        "For what reason is it recommended to take milk samples through a manhole?",
        "What is the definition of the term \"Operation TIR\"?",
        "What does the United Nations assessment rate mean?",
        "What does the term \"industrial rationalization\" mean?",
        "How many tests should be carried out for each side of an asymetrical double-glazing ?",
        "What is meant by \"non-automatic weighing instrument\"?",
        "What is the width of the type A top-side chafer compared to the width of the codend which is covered ?",
        "What does the term \"olive grower\" mean ?",
        "What does the term \"Official veterinarian\" mean ?",
        "What does \"directly controlled wheel\" mean ?",
        "What is the definition of \"national insurance office\"?",
        "What is the definition of insider trading ?",
        "Why should ECB and NCB have relevant mechanisms for control ?",
        "Whose responsibility is the control of the activities of employees , engaged in operations with market counterparties ?",
        "What should the exporter do in case his movement certificate EUR.1 has been stolen ?",
        "For research , pilot and demonstration projects , how often should a report be drawn up ?",
        "How often does the Commission compile a report on the quality of water in the member states ?",
        "What is the minimum number of participants in a network of excellence ?",
        "Which Article applies when converting euro amounts into other currencies ?",
        "What currencies are used for monetary amounts in the Oil Bulletin ?",
        "Approximately how much do most exporters receive a year in refunds ?",
        "What interest rate shall apply to overdue amounts owed to the Commission ?",
        "How much is one gram in Avoirdupois ounces ?",
        "How heavy is a \"bag\" of coffee ?",
        "What is the lowest speed in miles per hour which can be shown on a speedometer ?",
        "In which countries can yards and miles be used ?",
        "What is a protected sea area ?",
        "How far off the coast must a roll-on roll-off ferry go for common safety standards to apply ?",
        "What is an infected area?",
        "How fast does a tractor go ?",
        "What is an area of departure ?",
        "What is a frontier zone ?",
        "How do you find the maximum speed of a vehicle ?",
        "How do you express fuel consumption ?",
        "When can a staff member use a first-class ticket ?",
        "How long can a drift net be?",
        "By how much is it expected that road transport of goods will increase by 2010?",
        "How many trade names can be used for mineral water from a particular source ?",
        "What animal suffers from Aujeszky\'s disease?",
        "How must you not catch bluefin tuna ?",
        "Where is smoking forbidden ?",
        "Name a family of poisonous fish. ",
        "Where are you not allowed to spit ?",
        "How do you measure the stopping distance of a tractor?",
        "What creature does the small hive beetle affect ?",
        "What is the flashpoint of a substance ?",
        "What is the Latin name for dry rot fungus ?",
        "What is a byte?",
        "Give a definition for response time.",
        "What is meant by ash content?",
        "What is the main reason for international organised crime?",
        "What is the purpose of encouraging rail transport?",
        "Why does the Commission publicise its decisions?",
        "Why should the Eurotecnet and Force Advisory committees be combined?",
        "Why should the apricot standard of the UN commission for Europe be taken into account?",
        "Why should the wording of Article 11 of 83/181/EEC be composed accurately?",
        "How can you detect Ralstonia solanacearum?",
        "Why are court decisions in Kazakhstan not made public?",
        "Why was 93/504/EEC adopted?",
        "What is a broken egg?",
        "What does marketing mean?",
        "Define \"air pollution\".",
        "What is the minimum distance between \"snoods\" on a long fishing line?",
        "What is a microbiological process?",
        "For an animal dose what is meant by \"safety margin\"?",
        "When does the marketing year for cereals begin?",
        "Why should tractor makers specify the gear ratio and maximum rpm?",
        "Why should ships have proper medical supplies?",
        "What is the purpose of curing cheese?",
        "Why should it be possible to charge a premium on imported malt?",
        "Why is it necessary to establish fishing principles at European level?",
        "Why should countries prevent assets being dissipated?",
        "Why should 2125/95 be amended concerning Polish mushrooms?",
        "Why should claims for benefits be notified on a special form?",
        "Why must information on critical control points be recorded?",
        "What is know how?",
        "Why does the internal market need statistical standards?",
        "Why should bananas from ACP countries be allowed?",
        "Why should emergency exits be unobstructed?",
        "Why should 821/68 be adopted?",
        "Why must countries give EU certificates for vocational qualifications?",
        "Why should a herd book be in different sections?",
        "Why should the market for frozen mackerel be watched?",
        "What does \"group of seats\" mean?",
        "How much does cotton increase in weight after treatment with formic acid?",
        "Why are EU intervention measures needed for the tobacco market?",
        "What is the procedure by which the Executive Committee can ensure the proper application of the Schengen Convention?",
        "Why should operators return licences to the issuing agency after they have expired?",
        "Why should the structure of an ANIMO network be revised?",
        "What is the procedure for ensuring that milkfat cannot be separated?",
        "Why was the System of National Accounts adopted in 1993",
        "Why should confidential information be treated properly?",
        "What does standard price mean?",
        "What is a \"product group\"?",
        "What is the procedure for cleaning filter discs?",
        "What is the procedure by which a contractor should apply for an advance?",
        "What is the procedure for combining a \"supply table\" and a \"use table\"?",
        "What is the procedure for eliminating the effect of market dumping carried out by countries outside the EU?",
        "Define \"freezing of funds\".",
        "What is a posted worker?",
        "Why must documents sent to the commission be clearly labelled?",
        "What is the purpose of upgrading places where food is being processed?",
        "Why should there be free circulation of services in Europe?",
        "What is the purpose of giving electronic auctions an EU definition?",
        "What is the purpose of amending 77/270/Euratom in respect of nuclear power?",
        "Why should indicators for measuring the amount of violence be created?",
        "What is the reason for giving aid to dairies in respect of milk products?",
        "Why should contracts relating to products in 2202/96 be completed before a given date?",
        "What is the purpose of using monofilament streamer lines on swivels in fishing?",
        "Why should the origin of a cheese be stencilled on it?",
        "When did the European Council ask for a strategy in order to improve the interoperability of trains?",
        "Which ports should be deleted from the list of border inspection posts?",
        "How can unsafe abortions be reduced?",
        "What is the ozone layer?",
        "How can ghost fishing be fought?",
        "How will the trade in nuclear materials with Tajikistan be conducted?",
        "When did the European Parliament sign a resolution on the access to drugs for AIDS victims in developing countries?  ",
        "When has the plan to combat illegal immigration in the European Union been approved?",
        "Why should the use of lead-based capsules to cover containers be banned?",
        "On what will the interoperability of the trans-European high-speed rail network depend?",
        "Which country outside the Union may express its intention of taking part in military operations?",
        "What does a recognized language mean?",
        "Why has the coal industry been forced to embark on restructuring measures over the past years?",
        "Why will the media coverage of sport in 2004 be increased?",
        "According to what principles have buildings on campsites been built?",
        "What does \"national central banks\" mean?",
        "What does bluetongue mean?",
        "The use of which skins was banned?",
        "How are microenterprises defined with respect to other SMEs?",
        "For which uses can the use of  non-potable water be authorized ?",
        "When can tolls be set on motorways?",
        "Who will provide the translation services?",
        "What do taxes on wealth refers to?",
        "What is the aim of the spectrophotometric examination in the ultraviolet?",
        "When were the tsunamis in the Indian Ocean?",
        "What must the insulation and ventilation of buildings ensure?",
        "What is the aim of the radio spectrum policy in the Community",
        "Why are the Arctic indigenous at risk?",
        "Where must pigs not be kept?",
        "When did the  Council of Europe adopt a programme of action against corruption?",
        "How can CDs be distinguished?",
        "What is the objective for underground storage of waste?",
        "What is considered an emission?",
        "For who may the aerial application of herbicides be dangerous?",
        "Which bodies does EOTA bring together?",
        "What is the aim of The European Globalisation Adjustment Fund?",
        "What is the aim of the Commission in awarding a grant to the EIB?",
        "What is a \"road train\"?",
        "How will the number of sampling points in the islands be calculated?",
        "Who will be involved in radiotherapeutic practices?",
        "Why is the recruitment of teachers in Northern Ireland different?",
        "When were the categories of educational services set?",
        "Why is it appropriate to improve the measures against avian disease?",
        "Which rivers were considered as a buffer zone?",
        "What is the aim of the directive 89/552/EEC with respect to the TV?",
        "What is the name of the protocol about substances that damage the ozone layer?",
        "What is the aim of the UN's convention on climate change?",
        "How can aberrations in spermatogonial cells be detected?",
        "What does ear tag mean?",
        "What kind of cover do oil tankers need?",
        "On which days shall the TARGET system be closed?",
        "What is the definition of  \"arable land\"?",
        "What has influenced the increasing of the CTVs?",
        "What is the basis of the cohesion policy?",
        "What do recipients have to respect prior to receiving assistance?",
        "What does \"direct consumption\" mean?",
        "Why do the new psychoactive substances have to be included in the criminal law?",
        "What is the meaning of  \"non-scheduled substance\"?",
        "Where is the Europol Drugs Unit based?",
        "What is the aim of the PHARE drugs program?",
        "What is necessary  for animal health purposes?",
        "What does \"municipal waste\" mean?",
        "How many hours will comprise basic training for a doctor?",
        "What is the aim of the inter-university agreements?",
        "How will the commission of terrorist acts be prevented?",
        "Why is it justified to temporarily exempt the airports of Berlin?",
        "Where are bivalve molluscs of the species Acanthocardia tuberculatum found?",
        "What is a \"ro-ro ferry\"?",
        "What does \"transit State\" mean?",
        "How are trees used to obtain progeny?",
        "How will judges be appointed by the Council?",
        "What is the objective of EUSEC RD Congo?",
        "What are de main tasks of the European Bureau for Lesser-Used Languages?",
        "What does \"Computer Security Product\" mean?",
        "How will statistic data be sent to Eurostat?",
        "What does \"language endorsement\" include?",
        "Why has the European Union engaged itself in an action to promote the linguistic diversity in the Union?",
        "Why is it necessary to harmonise the inspection of the laboratories?",
        "Why has a level to be set  for harmonised MRPLs?",
        "For what reason was a committee for medicinal products created?",
        "What is the aim of the use of residues from the agrifoodstuffs?",
        "What is considered as biomass?",
        "For what reason was solicited an exception in the cost of production for 1999?",
        "What does \"general aviation\" mean?",
        "When was the Chicago Convention signed?",
        "What are homongenised vegetables?",
        "What is the procedure for colorants labelling on cosmetics?",
        "What is the aim of the amendment of the Combined Nomenclature of merchandises?",
        "How shall the classification of goods be determined?",
        "When was the resolution on implementation of financial services passed?",
        "Why could the TSI be modified?",
        "When should the external Specific Transmission Module  be ready?",
        "What is the goal of the promotion of GSM-R fitting by Member States?",
        "What is the goal of the police mission in Kinshasa(DRC)?",
        "Why is it necessary to make the definitions of classes of conformation and fat cover more precise?",
        "What are the goals of management plans to be drawn up by operators in the extractive industry?",
        "What is the procedure for import licence applications?",
        "Why has there been an upward adjustment for some producers?",
        "Why did the Commission sent market economy treatment and individual treatment claim forms to the Chinese companies?",
        "What is the procedure to resubmit a proposal?",
        "Why should supported actions  be concentrated on promoting sustainable growth?",
        "What does \"butter\" mean?",
        "What does the expression \"dairy spreads\" mean ?",
        "What does \"concentrated grape must\"  mean?",
        "Why is the extension of the system of cumulation desirable?",
        "What is the goal of the further treatment, with hydrogen, of lubricating oils?",
        "What is the procedure for voting to amend  a proposal ?",
        "Why should Regulations (EEC) No 1408/71 [3] and (EEC) No 574/72 [4] be amended?",
        "What is the aim of the establishment of an equivalent level of customs controls in the Community?",
        "What is the objective of the requirement of pre-arrival or pre-departure information for all goods ?",
        "What happened on September 9 2005?",
        "What is the goal of the negotiations with Host States?",
        "What are the objectives of the Lamfalussy process?",
        "What principles should the Commission respect in exercising its implementing powers?",
        "What is \"permanent pasture\"?",
        "What is the goal of adapting existing measures?",
        "What is potassium chloride ?",
        "What is the procedure used to set a normal value?",
        "What is the aim of the strenghtening of the efforts of the recipient countries?",
        "What is a telematic network?",
        "What is a signatory?",
        "What are regulated resources?",
        "What are anti-competitive activities?",
        "What is an alert threshold?",
        "What is an operator?",
        "What is the aim of consortia?",
        "What is the goal of the measures taken by the Community?",
        "Which is the aim of relating contracts to a certain minimum quantity?",
        "What is the procedure when a person has submitted a claim for family benefits to a not competent State?",
        "How is an application for a priori authorization made?",
        "How shall the letter of authority be issued?",
        "What is the procedure when authorities need the aid of appointed persons?",
        "What is the length of the validity of the document of compliance?",
        "Under which condition should documents of compliance and safety management certificates be recognized?",
        "How should the list of goods and services be worked?",
        "What is the main purpose of EAA?",
        "Why can institutional units be broken down into the same number of local KAUs?",
        "What are the greatest threats to the ideals of democracy ?",
        "What is the goal of the amendments to the 1974 International Convention for the Safety of Life at Sea ?",
        "What procedure is used to monitor compliance with safety rules concerning ships intending to enter a Community port?",
        "Why should area payment be restricted to certain areas?",
        "Which country has a very large number of small farms?",
        "What is the procedure when the area for which an aid is claimed exceeds the maximum area?",
        "Why is it impossible to establish a list of eligible varieties for the granting of the aid in the year 2005?",
        "What are the goals of the Audiovisual policy and content regulation ?",
        "Why should national regulatory authorities gather information from market players?",
        "What is the procedure for drawing up Community statistics ?",
        "What is the goal of EUROSTAT?",
        "Why should the scope of the measures eligible for aid from the EAGGF be extended?",
        "What is the condition under which a tenant farmer may transfer the released land to the owner?",
        "Why should any person entering pig holdings  comply with appropriate hygiene measures?",
        "What is the decision limit when no permitted limit has been established for a substance?",
        "What is the aim of adopting a high and uniform level of protection of the European citizen in civil aviation?",
        "What is an universal service?",
        "Which is the single European emergency call number  ?",
        "Why should the concept of labelling be clarified?",
        "What is the subject of the e-Europe initiative?",
        "Which parties signed the Schengen Agreement?",
        "What is the aim of the agreements on specialisation in production?",
        "Which animal species is affected by the \"white spot syndrome\"?",
        "What is meant by EAGGF?",
        "What should be done in the case of epizootic?",
        "Why should the Directive 64/432/EEC be modified?",
        "What is a third country supposed to do in order to be included in the list of third countries from which Member States are allowed to import products of animal origin? ",
        "What is the purpose of the Communities' own resources system?",
        "Which is the competent authority in Singapore for verifying and certifying the compliance of fishery and aquaculture products?",
        "What is the book value of a fixed asset?",
        "What is meant by depreciation? ",
        "What is meant by density?",
        "How is the real alcoholic strength by volume of spirit drinks calculated?",
        "Why are spirits distilled?",
        "What is the procedure to identify congeners in spirit drinks?",
        "What is the objective of the Monitoring Centre?",
        "When was the Energy Charter Treaty signed?",
        "On which principles is the Community policy in the field of environment based?",
        "What has been detected in fresh bovine meat from the United States of America?",
        "In which country has Anoplophora glabripennis (Motschulsky) been intercepted?",
        "According to the Council Directive 86/609/EEC, under which circumstances shall an animal not be used for experiments?",
        "What is a polymer?",
        "What should containers containing preparations sold to the general public and labelled as toxic be equipped with?",
        "What is the purpose of the Agreement of Luxembourg?",
        "Who retains responsibility for nuclear safety?",
        "Which products shall not be awarded the eco-label?",
        "Which decision has the Commonwealth of Australia agreed to accept in the context of GATT?",
        "How are soft ripened cheeses treated?",
        "How many tonnes of mutton, lamb and goat meat can Argentina export into the Community per year?",
        "Give a definition of natural mineral water.",
        "What does the net power test of an engine consist of?",
        "What aim did Denmark pursue in its letter dated 16 February 2001?",
        "What does Article 12 of the Agreement between the European Community , the Republic of Iceland and the Kingdom of Norway refer to?",
        "What is the scope of Eurodac?",
        "What was the objective of the \"Dublin Convention\" '?",
        "Which right does the Community air carriers have?",
        "Why must certain provisions of the bilateral air service agreements between Member States of the European Community and Georgia be modified?",
        "What does \"Moroccan fishing zone\" mean?",
        "How is babesiosis transmitted? ",
        "What are the Community's objectives according to Article 130r of the Treaty?",
        "What are the aims of the European Atomic Energy Community?",
        "What should be done in order to improve nuclear safety in central and eastern Europe and the CIS?",
        "What should packages of fishery products be furnished with?",
        "What is the maximum time limit within which eggs must be delivered to the consumer? ",
        "Why did a group of Commission experts visit Turkey?",
        "What is meant by \"duty-free replacement of goods procedure\"?",
        "What is the name of the airport in Amsterdam?",
        "What must the driver of a heavy goods vehicle registered after 1 October 1990 carry?",
        "What should be considered \"obstacles to trade\"?",
        "What does \"Community enterprise\" mean?",
        "What was the outcome of the Uruguay Round?",
        "What is the procedure to put products into free circulation under regional surveillance?",
        "What is meant by \"port and harbour authority\"?",
        "What is a chemical tanker?",
        "What is the procedure to enter the Host State's territory for EUFOR personnel?",
        "What does \"official correspondence of EUFOR\" refer to?",
        "What is the procedure to inspect baggage of EUFOR personnel?",
        "What is the aim of Commission Decision 2002/371/EC of 15 May 2002?",
        "Why is a monthly sero-epidemiological monitoring for African horse sickness carried out? ",
        "What is meant by raw milk?",
        "What is the procedure to attest the conformity of the products?",
        "What should be done in cases in which provisions concerning manufacturing require confidential treatment?",
        "What is the aim of the \"General Format of European Technical Approval\"?",
        "Why should water be protected and defended?",
        "Why has the Commission adopted protection measures in relation to avian influenza?",
        "Why shall the Treaties establishing the European Communities no longer be applied to Greenland?",
        "Why has the Commission been authorized on 8 December 2003 to negotiate with Ukraine?",
        "Why should the Employment Guidelines be fully reviewed only every three years?",
        "Why is cross-border distance selling important?",
        "Why has the Commission adopted protection measures in relation to Newcastle disease in Bulgaria?",
        "Why has Commission Decision 2005/734/EC of 19 October 2005 been adopted?",
        "What must a Member State do if it wants  to participate in the Environmental Impact Assessment procedure?",
        "How must fuel tanks be made?",
        "What must be done in order to ensure the safety of pressure equipment?",
        "What is the procedure to follow before issuing European approval for materials?",
        "How is the mass of the vehicle in running order measured?",
        "What does television advertising aim at?",
        "What shall a Member State which intends to inspect Community fishing vessels flying its flag do?",
        "What is the aim of the European Regional Development Fund?",
        "What is the purpose of an EGTC?",
        "Why shall a minimum price for the raw sugar exported by less developed countries be fixed?",
        "Who is appointed for six years by the Council of the European Atomic Energy Community?",
        "What is meant by gross weight?",
        "Why is the system of cumulation imposed?",
        "What is the main objective of producing electricity in public thermal plants?",
        "When are goods considered unfit for consumption?",
        "What denotes NUTS in the context of milk products?",
        "How should an invoice declaration be completed if done by hand?",
        "How is the carcass of bovines defined?",
        "What is the aim of starting consultations with Guinea in 2004?",
        "What does CAS RN stand for?",
        "Why is the registry of the Arbitration Committee attached to the Court of Justice?",
        "What is the screening procedure in case of doubts?",
        "Who must be notified when noticing a breach of the security measures or regulations?",
        "What is fixed for olive oil every year for no later than October 1st?",
        "What is a phonogram?",
        "What is the aim of creating a buffer stock of olive oil?",
        "What rights do performers have with respect to the reproduction in phonograms?",
        "What is meant by pure refined olive oil?",
        "What are import duties and taxes?",
        "Which is the Brockmann procedure to standardise aluminium oxide? ",
        "Why must the concentration of a certain chemical mixture used in cosmetic products be reduced ?",
        "What is the motivation to modify the quality standards for tulip bulbs? ",
        "What are the stages of customs clearance operations?",
        "Regarding the closure, what is the goal of producing adequate cowls and hoods? ",
        "Why must another method of recognition of higher-education diplomas be adopted? ",
        "What is the purpose of quick-freezing?",
        "What do traffic police expenditures comprise?",
        "What is meant by tin?",
        "What is the aim of the Kyoto Protocol in relation to greenhouse gas emissions for 2008-2012?",
        "How does a shipowner proceed if he fails to comply with his commitments to a scientific observer? ",
        "What is meant by taximeter?",
        "What is the objective of the annual outlook on tin production, consumption and trade?",
        "Why feeding-stuffs with additives should be provided with special labels? ",
        "For what purpose are the operating manuals made available to operational staff? ",
        "What is a CD-R disk?",
        "Why do Chinese originating parts used to assemble bikes fall outside the basic regulation? ",
        "How do you proceed in a swine holding pen if a suspected infectious disease of the reproduction tract appears? ",
        "Why should the EC actions for promoting equality between women and men be continued and consolidated? ",
        "What steps should a commander of a fishing vessel that wants to transship mackerel on another ship follow? ",
        "What procedure should be followed by an organization that wants to expand its safe harbor benefits to human resources information? ",
        "List new multimedia service elements. ",
        "How is the stratification method applied to the valuation of housing services in most countries? ",
        "For what purpose shall EC states adapt their own systems of agricultural statistics? ",
        "How are weighing instruments defined? ",
        "Related to the system of integrated accounts, why should the concept of territory of a Member State be clarified? ",
        "Under what conditions substances placed on the market for applicative research and development  receive an exemption for one year?",
        "Why is it necessary to establish a clear mark for equidae marked for slaughter? ",
        "What is the sampling process for hens raised on perches? ",
        "When did the EC first introduce measures to control the foot and mouth disease?",
        "Why Member States must require certain data and information from the importer from another Member State?",
        "Why can some alcohols or essential oils help in the preservation of cosmetic products? ",
        "How to determine non-volatile substances from the propionic acid? ",
        "Why should limits be established for the discharges of mercury into water?",
        "What is the purpose of providing support to development agents and vocational guidance experts?",
        "What is the goal of the reorganization of structures and procedures for management and coordination of the EC?",
        "How are the feedstocks defined?",
        "What is the common objective of joint research in controlled thermonuclear fusion and plasma physics?",
        "What is the seat reference point?",
        "What is the purpose of the vehicle identification number?",
        "What is the radio interference suppression equipment for tractors? ",
        "What is the purpose of the protective device of the vehicle transmission?",
        "In relation to vehicles , what may the Member States prohibit as from October 1, 1975?",
        "What is the aim in controlling the compulsory insurance cover against civil liability when crossing the frontier?",
        "What is hop powder? ",
        "How should workshop and warehousing charges be entered? ",
        "What is meant by 'obligation to carry' for transport undertakings'? ",
        "Why cannot the cost price of the olive oil be known at the time of contract conclusion? ",
        "How is the monthly transitional allowance for a former member of the Commission or of the Court calculated? ",
        "Why are special conditions laid down for the health status and analytical purity of cereals seeds? ",
        "What is the basic source of data for studies on agricultural holdings business operations? ",
        "What marks the end of 1963 for the reinsurance branches?",
        "What is the composition of the Advisory Committee on Vocational Training set up in 1963?",
        "Why does the EC support the financial consequences of the single market stage?",
        "When did the EU suggest that the Swiss Confederation concludes an agreement on the Swiss  participation in the operations in Congo?",
        "What does JRC signify in the context of nuclear activities?",
        "What does EIB denote in correlation with investments?",
        "What is the objective of the 33.5 million euros macro-financial assistance for Georgia from the EC?",
        "What is the use of the preloading device?",
        "What is a parcel when there is no land register? ",
        "How to determine the monthly amount of pension due to the survivor of a staff member who died in service?",
        "How are small-meshed nets defined? ",
        "According to a Council meeting in 1990, what measures are needed regarding cultural goods?",
        "What is transmitted annually by the Portuguese authorities before the authorized period for a type of fishing?",
        "What does rest mean for a driver?",
        "When was the import from EC of cheeses from goats' milk and Roquefort introduced in Australia, free of any quantitative restrictions?",
        "How must the fuel tanks be installed?"};
    
    
}
